Fix redirection when redirectionCookie is present before loggin in
cabinetoffice/gap-user-service pull request #195
Opened 2024-04-03 14:27 UTC by a-lor-cab

If a redirectionUrl is passed on v2/login, redirect the admin or superadmin to expected url instead of respective dashboard

## Description

Ticket # and link

Summary of the changes and the related issue. List any dependencies that are required for this change:

## Type of change

Please check the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes:

- [ ] Unit Test

- [ ] Integration Test (if applicable)

- [ ] End to End Test (if applicable)

## Screenshots (if appropriate):

Please attach screenshots of the change if it is a UI change:

# Checklist:

- [ ] If I have listed dependencies above, I have ensured that they are present in the target branch.
- [ ] I have performed a self-review of my code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation where applicable.
- [ ] I have ran cypress tests and they all pass locally.

2024-04-03 14:54 UTC, dominicwest requested changes
Looks good! just a couple small refactors I'd suggest

2024-04-03 14:54 UTC, dominicwest commented on src/main/java/gov/cabinetofice/gapuserservice/enums/LoginJourneyRedirect.java
> +    }
```suggestion
    private static String buildAdminRedirectionUrl(final GetRedirectUrlArgs getRedirectUrlArgs, final boolean isSuperAdmin) {
        if (getRedirectUrlArgs.redirectUrlCookie() != null)
            return getRedirectUrlArgs.redirectUrlCookie();
        final String dashboardRedirect = isSuperAdmin ? "/super-admin-dashboard" : "/dashboard";
        return getRedirectUrlArgs.adminBaseUrl() + "?redirectUrl=" + dashboardRedirect;
    }
```

2024-04-03 14:54 UTC, dominicwest commented on src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java
> +        return  redirect;
```suggestion
        deleteStateCookie(response);
        
        return new RedirectView(runStateMachine(redirectUrl, user, customJwtCookie.getValue(),
                user.hasAcceptedPrivacyPolicy(), userInfo));;
```
Should probably extract this deleteStateCookie to a function

2024-04-03 14:55 UTC, a-lor-cab commented on mockOneLogin/docker-compose.yml
> +      ["--global-response-templating", "--verbose"]
it adds the logs if u run the wiremock container in a non detached mode

2024-04-04 08:58 UTC, dominicwest reviewed
Final thought is around how the `redirectUrlParam` var we send to the login endpoint is actually sent. For example is it set when logging in from middleware?

2024-04-04 08:58 UTC, dominicwest commented on src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java
> +        return  redirect;
should still be able to inline return this

2024-04-04 09:21 UTC, a-lor-cab commented
> Final thought is around how the `redirectUrlParam` var we send to the login endpoint is actually sent. For example is it set when logging in from middleware?

both middlewares use an env variable for the loginUrl, both of them(if one login is enabled) have the redirectUrl query param in it.

apply/applicant/index.page which we use as home page for the login, also use the same env variable.

so looks like any attempt of login from the FE will have the redirectUrl param when they do hit the user service v2/login endpoint

2024-04-04 11:09 UTC, dominicwest approved these changes

2024-04-04 11:11 UTC, merged